### ISSUE TITLE
case文の定義

### ISSUE THREAD

**Issue by yuriacats** [yuriacats/csharp-shisoku#27]
switch文は以下のように定義できる
switch `Exp<T>` ?
`<T>` : {`statement[]`},
`<T>` : {`statement[]`},
| : {`statement[]`} ,

IF文は以下と導き出せる
switch `Exp<Bool>` ?
true : {`statement[]`},
|:{`statement[]`},

**Comment by KisaragiEffective** [comment]
if式を開始する開始するキーワードは`case`？

**Comment by yuriacats** [comment]
そう。そもそも概念上IFが存在しないようにしてみようかなと
