### ISSUE TITLE
[旧仕様]変数作成機能を追加

### ISSUE THREAD

**Issue by yuriacats** [yuriacats/csharp-shisoku#9]

**Comment by yuriacats** [comment]
関数定義を
const 関数名={ 引数名 | 型名 -> 処理を書く;}
const 関数名={ 引数名 |-> 処理を書く;}

変数定義を
var 変数名|型名=変数;

定数定義を
const 変数名|型名=変数;

型の別名定義を
type ailas 型名=型名;

**Comment by yuriacats** [comment]
引数が0のパターン
const 関数名 | Func ={| 返り値型 -> 処理を書く; } 
const 関数名 | Func = {| Int, (x, y)| Int -> return (x + y );}  

引数が2つのパターン
const 関数名 ={ | 型名,
　引数名| 型名,
　引数名| 型名,
-> 
　処理を書く
 }

関数名の返り値の型を絞りたい時
const 関数名 ={| 型名, 引数名| 型名, 引数名| 型名,-> 処理を書く }
関数呼び出し

関数名(
 引数名=変数,
 引数名=変数,
)

**Comment by yuriacats** [comment]
考え方

定義しますの意図
`=`
型名を補う時
`|`
すでに出ている概念同士に対して対応関係を示す時
`= `

同じ型に対して同一であるかの比較演算子
`==`
同一であるかの比較演算子のNot
`!=`

**Comment by yuriacats** [comment]
Int型の引数を3つとって足し算の結果を返す。
```
const IntAdd ={
leftHand | Int ,
rightHand | Int ,
->
return (leftHand + rightHand);
 }


const IntAddThree = {
firstInt | Int ,
secondInt | Int ,
thirdInt | Int ,
->
const intResalt | Int = IntAdd(
leftHand = IntAdd(
  leftHand = firstInt,
  rightHand = secondInt,
),
rightHand = thirdInt,
)
return ( intResalt )
}
```

**Comment by yuchiki** [comment]
「関数呼び出しじゃなくて、変数xに1を入れて、変数yに２を入れて、足す」みたいなのはどう書く？

**Comment by yuriacats** [comment]
{
| Int,
x | Int ,
y | Int ,
-> 
return ( x + y )
}| Int (
x = 1;
y = 2;
)

パッと思いついたのは、かなぁ冗長だけど。
{| Int, (x , y) | Int -> return (x + y); } (x=1,y=2)

**Comment by yuriacats** [comment]
```
{| Int->
var x | Int := 1;
var y | Int := 2;
retun (x + y);
}()

Entry(IsAdd())
```

という構文が行儀が良くていいよと言いつつ
```
var x | Int = 1;
var y | Int = 2;
(x + y);

**Comment by yuriacats** [comment]
const 変数名= 数字
を受け入れるようにする。

**Comment by yuriacats** [comment]
Lex 文字列を受け入れるようにする。
TokenConst()
TokenVariable()
TokenIdentfier(string Name)
TokenDefinision()  (:=)

**Comment by yuriacats** [comment]
#18 でトーカナイザー作成。
